# Default initial positions for turtlebot_arm's ros2_control fake system

initial_positions:
  arm_elbow_flex_joint: 0
  arm_shoulder_lift_joint: 0
  arm_shoulder_pan_joint: 0
  arm_wrist_flex_joint: 0