# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      